name: Documentation

on:
  push:
    branches: [ main ]

jobs:
  docs:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup PowerShell
      uses: PowerShell/PowerShell-For-GitHub-Actions@v2
      with:
        pwsh-version: '7.4'

    - name: Install PlatyPS
      shell: pwsh
      run: Install-Module PlatyPS -Force -Scope CurrentUser

    - name: Import module
      shell: pwsh
      run: |
        Import-Module "$PWD/src/technification-ps-toolkit.psd1" -Force
        Get-Module technification-ps-toolkit | Format-List Name,Version,Path

    - name: Generate documentation
      shell: pwsh
      run: |
        New-MarkdownHelp -Module technification-ps-toolkit -OutputFolder docs -Force
        Update-MarkdownHelp -Path docs -Force

    - name: Commit documentation
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Update documentation"
        branch: main