name: Documentation

on:
  push:
    branches: [ main ]

jobs:
  docs:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install PlatyPS
      shell: pwsh
      run: |
        Install-Module PlatyPS -Repository PSGallery -Force -Scope CurrentUser -Confirm:$false

    - name: Import module
      shell: pwsh
      run: |
        Import-Module "$env:GITHUB_WORKSPACE\src\technification-ps-toolkit.psd1" -Force
        Get-Module technification-ps-toolkit | Format-List Name,Version,Path
        Get-Command -Module technification-ps-toolkit

    - name: Generate documentation
      shell: pwsh
      run: |
        New-Item -ItemType Directory -Force -Path docs | Out-Null
        New-MarkdownHelp -Module technification-ps-toolkit -OutputFolder docs -Force
        Update-MarkdownHelp -Path docs -Force

    - name: Commit documentation
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Update documentation"
        branch: main
